### ISSUE TITLE
Bad processing of extensions

### ISSUE THREAD

**Issue by pkocandr** [Commonjava/cartographer#95]
It seems there are some plugin-specific extensions (the plugin is cxf-xjc-plugin)  used for example in org.apache.cxf:cxf-rt-transports-http:2.7.17.redhat-1. The processing of the pom rises 2 exceptions:

```
    11:35:31.551 [carto-aggregator-2] ERROR o.c.c.graph.MavenModelProcessor - org.apache.cxf:cxf-rt-transports-http:2.7.17.redhat-1: Build extension is invalid! Reason: ProjectId must contain non-empty groupId AND artifactId. (Given: 'null':'null'). Skipping:
     
    <?xml version="1.0" encoding="UTF-8"?><extension>org.apache.cxf.xjcplugins:cxf-xjc-pl:${cxf.xjc-utils.version}</extension>
     
     
     
    org.commonjava.maven.atlas.ident.ref.InvalidRefException: ProjectId must contain non-empty groupId AND artifactId. (Given: 'null':'null')
            at org.commonjava.maven.atlas.ident.ref.SimpleProjectRef.<init>(SimpleProjectRef.java:41) ~[atlas-identities-0.15.3-SNAPSHOT.jar:na]
            at org.commonjava.maven.atlas.ident.ref.SimpleProjectVersionRef.<init>(SimpleProjectVersionRef.java:60) ~[atlas-identities-0.15.3-SNAPSHOT.jar:na]
            at org.commonjava.maven.atlas.ident.ref.SimpleProjectVersionRef.<init>(SimpleProjectVersionRef.java:79) ~[atlas-identities-0.15.3-SNAPSHOT.jar:na]
            at org.commonjava.maven.galley.maven.model.view.MavenGAVView.asProjectVersionRef(MavenGAVView.java:101) ~[aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at org.commonjava.cartographer.graph.MavenModelProcessor.addExtensionUsages(MavenModelProcessor.java:120) [aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at org.commonjava.cartographer.graph.MavenModelProcessor.readRelationships(MavenModelProcessor.java:67) [aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at org.commonjava.aprox.depgraph.discover.AproxModelDiscoverer.discoverRelationships(AproxModelDiscoverer.java:107) [aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at org.commonjava.aprox.depgraph.discover.AproxModelDiscoverer$Proxy$_$$_WeldClientProxy.discoverRelationships(Unknown Source) [aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at org.commonjava.aprox.depgraph.discover.AproxProjectGraphDiscoverer.discoverRelationships(AproxProjectGraphDiscoverer.java:127) [aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at org.commonjava.aprox.depgraph.discover.AproxProjectGraphDiscoverer$Proxy$_$$_WeldClientProxy.discoverRelationships(Unknown Source) [aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at org.commonjava.cartographer.INTERNAL.graph.agg.DiscoveryRunnable.run(DiscoveryRunnable.java:80) [aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
            at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
    11:35:31.551 [carto-aggregator-2] ERROR o.c.c.graph.MavenModelProcessor - org.apache.cxf:cxf-rt-transports-http:2.7.17.redhat-1: Build extension is invalid! Reason: ProjectId must contain non-empty groupId AND artifactId. (Given: 'null':'null'). Skipping:
     
    <?xml version="1.0" encoding="UTF-8"?><extension>org.apache.cxf.xjcplugins:cxf-xjc-dv:${cxf.xjc-utils.version}</extension>
     
     
     
    org.commonjava.maven.atlas.ident.ref.InvalidRefException: ProjectId must contain non-empty groupId AND artifactId. (Given: 'null':'null')
            at org.commonjava.maven.atlas.ident.ref.SimpleProjectRef.<init>(SimpleProjectRef.java:41) ~[atlas-identities-0.15.3-SNAPSHOT.jar:na]
            at org.commonjava.maven.atlas.ident.ref.SimpleProjectVersionRef.<init>(SimpleProjectVersionRef.java:60) ~[atlas-identities-0.15.3-SNAPSHOT.jar:na]
            at org.commonjava.maven.atlas.ident.ref.SimpleProjectVersionRef.<init>(SimpleProjectVersionRef.java:79) ~[atlas-identities-0.15.3-SNAPSHOT.jar:na]
            at org.commonjava.maven.galley.maven.model.view.MavenGAVView.asProjectVersionRef(MavenGAVView.java:101) ~[aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at org.commonjava.cartographer.graph.MavenModelProcessor.addExtensionUsages(MavenModelProcessor.java:120) [aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at org.commonjava.cartographer.graph.MavenModelProcessor.readRelationships(MavenModelProcessor.java:67) [aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at org.commonjava.aprox.depgraph.discover.AproxModelDiscoverer.discoverRelationships(AproxModelDiscoverer.java:107) [aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at org.commonjava.aprox.depgraph.discover.AproxModelDiscoverer$Proxy$_$$_WeldClientProxy.discoverRelationships(Unknown Source) [aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at org.commonjava.aprox.depgraph.discover.AproxProjectGraphDiscoverer.discoverRelationships(AproxProjectGraphDiscoverer.java:127) [aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at org.commonjava.aprox.depgraph.discover.AproxProjectGraphDiscoverer$Proxy$_$$_WeldClientProxy.discoverRelationships(Unknown Source) [aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at org.commonjava.cartographer.INTERNAL.graph.agg.DiscoveryRunnable.run(DiscoveryRunnable.java:80) [aprox-embedder-savant-0.25.2-SNAPSHOT.jar:na]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
            at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
```

These plugin extensions are defined by a string GAV, not by separated xml tags for artifactId etc. But I think it was not intention to process anything but build/extensions/extension possibly wrapped in a profile, right? In this case the path is build/plugins/plugin/configuration/extensions/extension. On the other hand they seem to be build-time dependencies so not sure what is the correct solution.

**Comment by jdcasey** [comment]
Yep, looks like we need to tighten up the xpath used to find extensions.

**Comment by jdcasey** [comment]
closing this in favor of the galley issue.
